//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkInOut
    {
        public int Id { get; set; }
        public int ParkIn { get; set; }
        public int ParkOut { get; set; }
    }
}
