//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartParkingDBEntities : DbContext
    {
        public SmartParkingDBEntities()
            : base("name=SmartParkingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactUsEmail> ContactUsEmails { get; set; }
        public virtual DbSet<ParkingSlot> ParkingSlots { get; set; }
        public virtual DbSet<ParkInOut> ParkInOuts { get; set; }
        public virtual DbSet<UserBooking> UserBookings { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<ActiveUser> ActiveUsers { get; set; }
        public virtual DbSet<FreeSpot> FreeSpots { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
    }
}
